name: Docker Build and Publish

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  ## define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      ## https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      ## https://github.com/docker/build-push-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      ## https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ## github.repository as <account>/<repo>
      - name: set lowercase image name
        run: |
          echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
        env:
          IMAGE_NAME: ${{ github.repository }}

      ## https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.IMAGE_NAME_LC }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}